const fs = require('fs');
const path = require('path');
const prompts = require('prompts');
const api = require('../../api');
const auth = require('../../auth');
const projectLink = require('../../project-link');
const logger = require('../../utils/logger');

const subcommand = process.argv[3] || 'ls';
const envName = process.argv[4];
const envValue = process.argv[5];
const envTarget = process.argv[6] || 'development';

async function run() {
  const token = auth.getToken();
  const linked = projectLink.loadLink();
  
  switch (subcommand) {
    case 'ls':
    case 'list':
      await listEnv(token, linked);
      break;
    case 'add':
      await addEnv(token, linked);
      break;
    case 'rm':
    case 'remove':
      await removeEnv(token, linked);
      break;
    case 'pull':
      await pullEnv(token, linked);
      break;
    case 'run':
      await runWithEnv();
      break;
    default:
      console.log('⚙️  Environment Variables Management\n');
      console.log('USAGE:');
      console.log('  ants env ls                  List environment variables');
      console.log('  ants env add <name> [value]  Add environment variable');
      console.log('  ants env rm <name>           Remove environment variable');
      console.log('  ants env pull [file]         Pull env vars to local file');
      console.log('  ants env run -- <command>    Run command with env vars');
      process.exit(0);
  }
}

async function listEnv(token, linked) {
  console.log('📋 Environment Variables\n');
  
  if (!linked) {
    console.log('⚠️  No project linked');
    console.log('💡 Run `ants link` first');
    return;
  }
  
  console.log(`📦 Project: ${linked.projectName}`);
  console.log('');
  
  try {
    const res = await api.get(`/api/env/${linked.projectId}`, { token });
    
    if (res.status === 200 && res.data?.vars) {
      console.log('NAME'.padEnd(25) + 'TARGET'.padEnd(15) + 'VALUE');
      console.log('─'.repeat(60));
      for (const v of res.data.vars) {
        const masked = v.value ? v.value.substring(0, 4) + '••••' : '(empty)';
        console.log(v.name.padEnd(25) + v.target.padEnd(15) + masked);
      }
    } else {
      console.log('ℹ️  No environment variables configured');
    }
  } catch (err) {
    console.log('ℹ️  No environment variables configured');
    console.log(`   (API: ${err.message})`);
  }
}

async function addEnv(token, linked) {
  let name = envName;
  let value = envValue;
  
  if (!name) {
    const response = await prompts([
      { type: 'text', name: 'name', message: 'Variable name' },
      { type: 'password', name: 'value', message: 'Variable value' },
      { type: 'select', name: 'target', message: 'Target environment',
        choices: [
          { title: 'development', value: 'development' },
          { title: 'preview', value: 'preview' },
          { title: 'production', value: 'production' },
        ],
      },
    ]);
    
    name = response.name;
    value = response.value;
  }
  
  if (!name) {
    console.log('❌ Variable name is required');
    process.exit(1);
  }
  
  try {
    const res = await api.post(`/api/env/${linked?.projectId || 'local'}`, {
      name,
      value,
      target: envTarget,
    }, { token });
    
    if (res.status === 200 || res.status === 201) {
      console.log(`✅ Added ${name}=${value ? '****' : '(empty)'} (${envTarget})`);
      logger.info(`Env added: ${name}`);
    } else {
      console.error(`❌ Failed to add: ${res.status}`);
    }
  } catch (err) {
    console.error(`❌ Failed to add: ${err.message}`);
  }
}

async function removeEnv(token, linked) {
  if (!envName) {
    console.log('❌ Variable name is required');
    console.log('USAGE: ants env rm <name>');
    process.exit(1);
  }
  
  try {
    const res = await api.delete(`/api/env/${linked?.projectId || 'local'}/${envName}`, { token });
    
    if (res.status === 200) {
      console.log(`✅ Removed ${envName}`);
      logger.info(`Env removed: ${envName}`);
    } else {
      console.error(`❌ Failed to remove: ${res.status}`);
    }
  } catch (err) {
    console.error(`❌ Failed to remove: ${err.message}`);
  }
}

async function pullEnv(token, linked) {
  const outputFile = process.argv[4] || '.env';
  
  console.log(`📥 Pulling environment variables to ${outputFile}...\n`);
  
  if (!linked) {
    console.log('⚠️  No project linked — using local config');
  }
  
  const configPath = path.join(process.cwd(), 'ants.config.json');
  let envVars = {};
  
  if (fs.existsSync(configPath)) {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    envVars = config.env || {};
  }
  
  if (Object.keys(envVars).length === 0) {
    console.log('ℹ️  No environment variables found');
    return;
  }
  
  let content = '# Generated by ants env pull\n';
  content += `# ${new Date().toISOString()}\n\n`;
  
  for (const [key, value] of Object.entries(envVars)) {
    content += `${key}=${value}\n`;
  }
  
  fs.writeFileSync(outputFile, content);
  console.log(`✅ Pulled ${Object.keys(envVars).length} variables to ${outputFile}`);
  logger.info(`Env pulled to ${outputFile}`);
}

async function runWithEnv() {
  const { execSync } = require('child_process');
  
  const cmdIndex = process.argv.indexOf('--');
  if (cmdIndex === -1) {
    console.log('❌ Command is required after --');
    console.log('USAGE: ants env run -- <command>');
    process.exit(1);
  }
  
  const cmd = process.argv.slice(cmdIndex + 1).join(' ');
  
  const configPath = path.join(process.cwd(), 'ants.config.json');
  if (fs.existsSync(configPath)) {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    if (config.env) {
      for (const [key, value] of Object.entries(config.env)) {
        process.env[key] = value;
      }
    }
  }
  
  const envFile = path.join(process.cwd(), '.env');
  if (fs.existsSync(envFile)) {
    const lines = fs.readFileSync(envFile, 'utf8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const [key, ...rest] = trimmed.split('=');
        process.env[key.trim()] = rest.join('=').trim();
      }
    }
  }
  
  console.log(`🏃 Running: ${cmd}\n`);
  
  try {
    execSync(cmd, { stdio: 'inherit' });
  } catch (err) {
    process.exit(err.status || 1);
  }
}

run();
